/**
 * Cipherguard ~ Open source password manager for teams
 * Copyright (c) Khulnasoft Ltd' (https://www.cipherguard.khulnasoft.com)
 *
 * Licensed under GNU Affero General Public License version 3 of the or any later version.
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Khulnasoft Ltd' (https://www.cipherguard.khulnasoft.com)
 * @license       https://opensource.org/licenses/AGPL-3.0 AGPL License
 * @link          https://www.cipherguard.khulnasoft.com Cipherguard(tm)
 * @since         2.0.0
 */
/**
 * CIPHERGURD CONFIGURATION FILE
 *
 * This is a generated configuration file, which was generated by the cipherguard web installer.
 *
 * To see all available options, you can refer to the default.php file, or replace this file
 * by a copy of cipherguard.default.php
 * Do not modify default.php or you may break your upgrade process.
 *
 * Read more about how to install cipherguard: https://www.cipherguard.khulnasoft.com/help/tech/install
 * Any issue, check out our FAQ: https://www.cipherguard.khulnasoft.com/faq
 * An installation issue? Ask for help to the community: https://community.cipherguard.khulnasoft.com/
 */
return [
    'App' => [
        // A base URL to use for absolute links.
        // The url where the cipherguard instance will be reachable to your end users.
        // This information is need to render images in emails for example
        'fullBaseUrl' => '<?= $config['options']['full_base_url'] ?>',
    ],

    // Database configuration.
    'Datasources' => [
        'default' => [<?php foreach ($config['database'] as $key => $value) {
echo "
            '$key' => '$value',";
    }?>

        ],
    ],

    'cipherguard' => [
        // GPG Configuration.
        // The keyring must be owned and accessible by the webserver user.
        // Example: www-data user on Debian
        'gpg' => [
            // Main server key.
            'serverKey' => [
                // Server private key fingerprint.
                'fingerprint' => '<?= $config['gpg']['fingerprint'] ?>',
                'public' => CONFIG . DS . 'gpg' . DS . 'serverkey.asc',
                'private' => CONFIG . DS . 'gpg' . DS . 'serverkey_private.asc',
            ],
        ],
        'ssl' => [
            'force' => <?= $config['options']['force_ssl'] ? 'true' : 'false' ?>,
        ]
    ],
];
